/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Common.Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ExchangeCDConfig : TBase
  {
    private int _itemType;
    private int _initData;
    private int _maxData;
    private int _cd;

    public int ItemType
    {
      get
      {
        return _itemType;
      }
      set
      {
        __isset.itemType = true;
        this._itemType = value;
      }
    }

    public int InitData
    {
      get
      {
        return _initData;
      }
      set
      {
        __isset.initData = true;
        this._initData = value;
      }
    }

    public int MaxData
    {
      get
      {
        return _maxData;
      }
      set
      {
        __isset.maxData = true;
        this._maxData = value;
      }
    }

    public int Cd
    {
      get
      {
        return _cd;
      }
      set
      {
        __isset.cd = true;
        this._cd = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool itemType;
      public bool initData;
      public bool maxData;
      public bool cd;
    }

    public ExchangeCDConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              ItemType = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              InitData = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.I32) {
              MaxData = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              Cd = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ExchangeCDConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.itemType) {
        field.Name = "itemType";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ItemType);
        oprot.WriteFieldEnd();
      }
      if (__isset.initData) {
        field.Name = "initData";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(InitData);
        oprot.WriteFieldEnd();
      }
      if (__isset.maxData) {
        field.Name = "maxData";
        field.Type = TType.I32;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(MaxData);
        oprot.WriteFieldEnd();
      }
      if (__isset.cd) {
        field.Name = "cd";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Cd);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ExchangeCDConfig(");
      sb.Append("ItemType: ");
      sb.Append(ItemType);
      sb.Append(",InitData: ");
      sb.Append(InitData);
      sb.Append(",MaxData: ");
      sb.Append(MaxData);
      sb.Append(",Cd: ");
      sb.Append(Cd);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
