/**
 * Autogenerated by script gen tool
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System.Collections.Generic;
using ExcelImproter.Framework.Handler;
using ExcelImproter.Framework.Importer;
using ExcelImproter.Framework.Reader;
using GameConfigTools.Util;

namespace ExcelImproter.Project
{
    public partial class DiyCharConfigHandler : ExcelConfigHandlerBase
    {
		private int id;
		private int positionId;
		private int vertexid;
		private int radius;
		private int min;
		private int max;
		private int dirx;
		private int diry;
		private int dirz;
    
        protected override void AutoParasTable(List<ExcelTable> sheetValues, ref string errMsg)
        {
            OnAutoParasBegin();

            if (sheetValues == null || sheetValues.Count == 0)
            {
                return;
            }
            for (int tableIndex = 0; tableIndex < sheetValues.Count; ++tableIndex)
            {
                List<List<string>> values = sheetValues[tableIndex].Data;
                for (int i = 0; i < values.Count; i++)
                {
                    if (!VaildUtil.IsLineNotNull(values[i]))
                    {
                        continue;
                    }
                    int row = i + 1;

if (!VaildUtil.TryConvert(values[i][0], out id,int.MinValue,int.MaxValue))
{
	errMsg = string.Format("{8} {0}.xlsx sheet:[{1}] [{2},{3}]读取出现错误，{4}必须为{5} - {6} {7}型", this.GetConfigPath(), tableIndex, row,0+1, id,int.MinValue,int.MaxValue,"int","id");
	return;
}
if (!VaildUtil.TryConvert(values[i][2], out positionId,int.MinValue,int.MaxValue))
{
	errMsg = string.Format("{8} {0}.xlsx sheet:[{1}] [{2},{3}]读取出现错误，{4}必须为{5} - {6} {7}型", this.GetConfigPath(), tableIndex, row,2+1, positionId,int.MinValue,int.MaxValue,"int","positionId");
	return;
}
if (!VaildUtil.TryConvert(values[i][3], out vertexid,int.MinValue,int.MaxValue))
{
	errMsg = string.Format("{8} {0}.xlsx sheet:[{1}] [{2},{3}]读取出现错误，{4}必须为{5} - {6} {7}型", this.GetConfigPath(), tableIndex, row,3+1, vertexid,int.MinValue,int.MaxValue,"int","vertexid");
	return;
}
if (!VaildUtil.TryConvert(values[i][4], out radius,int.MinValue,int.MaxValue))
{
	errMsg = string.Format("{8} {0}.xlsx sheet:[{1}] [{2},{3}]读取出现错误，{4}必须为{5} - {6} {7}型", this.GetConfigPath(), tableIndex, row,4+1, radius,int.MinValue,int.MaxValue,"int","radius");
	return;
}
if (!VaildUtil.TryConvert(values[i][5], out min,int.MinValue,int.MaxValue))
{
	errMsg = string.Format("{8} {0}.xlsx sheet:[{1}] [{2},{3}]读取出现错误，{4}必须为{5} - {6} {7}型", this.GetConfigPath(), tableIndex, row,5+1, min,int.MinValue,int.MaxValue,"int","min");
	return;
}
if (!VaildUtil.TryConvert(values[i][6], out max,int.MinValue,int.MaxValue))
{
	errMsg = string.Format("{8} {0}.xlsx sheet:[{1}] [{2},{3}]读取出现错误，{4}必须为{5} - {6} {7}型", this.GetConfigPath(), tableIndex, row,6+1, max,int.MinValue,int.MaxValue,"int","max");
	return;
}
if (!VaildUtil.TryConvert(values[i][7], out dirx,int.MinValue,int.MaxValue))
{
	errMsg = string.Format("{8} {0}.xlsx sheet:[{1}] [{2},{3}]读取出现错误，{4}必须为{5} - {6} {7}型", this.GetConfigPath(), tableIndex, row,7+1, dirx,int.MinValue,int.MaxValue,"int","dirx");
	return;
}
if (!VaildUtil.TryConvert(values[i][8], out diry,int.MinValue,int.MaxValue))
{
	errMsg = string.Format("{8} {0}.xlsx sheet:[{1}] [{2},{3}]读取出现错误，{4}必须为{5} - {6} {7}型", this.GetConfigPath(), tableIndex, row,8+1, diry,int.MinValue,int.MaxValue,"int","diry");
	return;
}
if (!VaildUtil.TryConvert(values[i][9], out dirz,int.MinValue,int.MaxValue))
{
	errMsg = string.Format("{8} {0}.xlsx sheet:[{1}] [{2},{3}]读取出现错误，{4}必须为{5} - {6} {7}型", this.GetConfigPath(), tableIndex, row,9+1, dirz,int.MinValue,int.MaxValue,"int","dirz");
	return;
}
                    
                    
                    OnAutoParasLine(tableIndex,row,values[i],ref errMsg);
                    if (!string.IsNullOrEmpty(errMsg))
                    {
                        return;
                    }
                    
                }
            }
        }
    }
}